In [1]:
import numpy as np

In [4]:
my=[1,2,3,4,5,6]

In [5]:
np.array(my)

array([1, 2, 3, 4, 5, 6])

In [15]:
my_1=[1,2,3,4,5,6]
my_2=[1,2,3,4,5,6]
my_3=[1,3,3,4,5,6]
arr=np.array([my_1,my_2,my_3])

In [16]:
arr

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 3, 3, 4, 5, 6]])

In [17]:
arr[0:2,0:2]

array([[1, 2],
       [1, 2]])

In [18]:
arr=np.random.randn(4,4)

In [19]:
arr

array([[-0.90611809, -1.21883832,  0.49463062,  0.32923963],
       [-0.1289906 ,  1.26319667,  0.84221861, -0.54446758],
       [ 0.09840235,  1.12001034,  0.16373309,  0.33613572],
       [ 0.01013552, -0.09580869,  0.8254695 , -0.09883419]])